### ISSUE TITLE
Look at variance of parent fitness

### ISSUE THREAD

**Issue by NicMcPhee** [NicMcPhee/XO-bias-study#23]
We should collect and explore the difference in fitness of parents, and how that relates to the effect of XO bias. Bill Langdon proposed this, and I think some of the Hampshire folks have suggested it as well. Bill pointed out that there's a reasonable chance that things like high tournament sizes will give us higher and more similar fitness for the two parents. If so, then XO bias isn't going to have much or any effect in those situations.

So if we collected that data (it's not something we currently have) for perhaps a couple of configurations (but by no means all, given the timing) that would probably be informative. It might also give us a legitimate reason to care less about many of those configurations where bias doesn't seem to be having much impact.

We'd have to add some code to ECJ that would compute the difference in fitnesses and output or collect those. Would we want just the average for each generation, or the full distribution for each generation?

**Comment by NicMcPhee** [comment]
There are three things that I can think of that could potentially affect the difference in the fitness of parents:
* Population size: Larger populations are presumably more diverse, which could increase the differences.
* Tournament size: Large tournaments are more likely to get "good" individuals, which could reduce the differences between parents.
* Elitism: Lots of elitism might make it more likely to get "good" individuals in the population and therefore in the tournaments, potentially reducing differences.

So it would be useful to look at the impact of each of these three things (separately, and perhaps together) on the difference of parental fitness.

**Comment by NicMcPhee** [comment]
Do we think we need to do runs with different levels of bias? If we think bias would affect the difference in parental fitness then we probably should, but I don't have a great sense of whether that will be the case or not.

**Comment by NicMcPhee** [comment]
I think I'm only going to do 10 or 20 runs of each configuration, at least for starters. The detailed behavior of the runs is likely to vary quite a bit, and all we're really after is whether there's some sense of a relationship between the difference and the effectiveness of bias. If it all looks like mud after a few runs we can walk away, but if it looks interesting then we can do more runs and dig into it further.

**Comment by MKDramdahl** [comment]
10 or 20 runs sounds adequate.

At least in the initial runs, I would not think different levels of bias will be necessary. If after the initial runs we think it could have an effect, it might be worth looking at.

**Comment by NicMcPhee** [comment]
That all sounds reasonable; I'll set that up and get it rolling.

**Comment by NicMcPhee** [comment]
This is essentially the same as Issue #30 (not sure why/how I ended up duplicating it), so I'm going to call this done as well.
