### ISSUE TITLE
Add text to the Results section

### ISSUE THREAD

**Issue by NicMcPhee** [NicMcPhee/XO-bias-study#37]
At the moment it's mostly just plot after plot after plot, and we need to:
* Add text in places (including expand the captions in places)
* Remove plots we're not going to use

**Comment by MKDramdahl** [comment]
Results section is currently a bit of a mess (my fault, my fault! - I have a terrible habit of making something worse before making it better), but I need sleep. I will get back on the task of adding text/cleaning this up tomorrow.

**Comment by NicMcPhee** [comment]
No worries – thanks for all your work. My experience is that every paper needs someone to bang out some rough text for starters. Once that's there, then people can edit like crazy :-).

**Comment by NicMcPhee** [comment]
I think we have a reasonable draft of the Results section now.
