### ISSUE TITLE
Construct the bibliography

### ISSUE THREAD

**Issue by NicMcPhee** [NicMcPhee/XO-bias-study#40]
A serious weakness of the paper as it stands is that we have basically no bibliography that refers to other people's work. Someone should probably do some searching for at least thinly related work. No one I've talked to seems to think anyone has done this, so I'm not too worried that we're duplicating previous work, but there's bound to be work that is at least dimly similar.

What might we search for?
* Parent selection
* Genetic programming root parent
* Parent ordering
* Difference in parent fitness

Other thoughts?

**Comment by NicMcPhee** [comment]
You might also look at the GP Bibliography that Bill Langdon maintains: http://www.cs.bham.ac.uk/~wbl/biblio/

**Comment by NicMcPhee** [comment]
This is in really good shape now; we're just waiting for @donat056 to add a couple of other bib entries that he found where people did things with asymmetries.

**Comment by donat056** [comment]
Added the articles.

**Comment by NicMcPhee** [comment]
Thanks!
