### ISSUE TITLE
Remove old stuff and extra plots from Ordertree section

### ISSUE THREAD

**Issue by NicMcPhee** [NicMcPhee/XO-bias-study#42]
From @MKDramdahl on the question of which plots to keep/use in the Ordertree section:
> In fact, the more I think about it the more I am inclined to just say drop the first OrderTree and the K-Landscape plot and keep the second OrderTree plot. More information without the repetition.

> Also, I believe we should drop the earlier plots with a population size of 500, as these two are inconsistent with the rest of our data collection treatments.

I think these are both excellent suggestions, so I made a to-do out of them :-)

**Comment by MKDramdahl** [comment]
I am going to go ahead and mark this as complete, even though I left the K-Landscape figure in there. The OrderTree figures are cleared out, anyway, and there is a good chance I will probably clear out some other graphs in my attempts to organize the results section tonight. Everything is still in the plots folder, however, so if I am a jerk and remove something that anyone else thinks is necessary, they can pretty easily go ahead and add it back in.
